### ISSUE TITLE
Error when dumping.

### ISSUE THREAD

**Issue by thautwarm** [Cm-lang/Cmc#4]
发现的问题如下：  
- 函数(lambda)被定义当且仅当函数名为`main`。
- `VariableDeclaration`类型的变量，当定义类型为`LambdaExpression`时，其（包括`main`函数)`Dump`方法出错，报错为  
  `System.NullReferenceException: Object reference not set to an instance of an object`。

**Comment by ice1000** [comment]
请提供对应的代码

**Comment by ice1000** [comment]
你为什么在我修复bug之前就close了。。。 :joy:
