### ISSUE TITLE
Choosing a LLVM binding for C#

### ISSUE THREAD

**Issue by ice1000** [Cm-lang/Cmc#5]
The Microsoft half-official LLVM binding for C# is poorly maintained.

Currently this project is using swigged-llvm.

**Comment by ice1000** [comment]
The maintainer of LLVM# said they plan to upgrade it to llvm 5 + the newest .net toolchain.

Seems that we have to wait patiently. :sob:

@SmallLuma @thautwarm

**Comment by ice1000** [comment]
LLVM# progress very fast.

**Comment by AkimotoAkari** [comment]
Ah, i think we may pay more atention to real-world machine codes ... 8086 is a good idea?:)

**Comment by ice1000** [comment]
@AkimotoAkari Pull requests are welcomed :smiley:

**Comment by ice1000** [comment]
LLVM# has released some early access packages.

Should we have a try now? @thautwarm

**Comment by thautwarm** [comment]
随便你。

2017年9月18日 上午12:03，"Tesla Ice Zhang" <notifications@github.com<mailto:notifications@github.com>>写道：

LLVM# has released some early access packages.

Should we have a try now? @thautwarm<https://github.com/thautwarm>

**Comment by ice1000** [comment]
今天起床这么早啊😯

**Comment by thautwarm** [comment]
要上课好不好

2017年9月18日 上午8:35，"Tesla Ice Zhang" <notifications@github.com<mailto:notifications@github.com>>写道：

今天起床这么早啊😯

**Comment by ice1000** [comment]
大新闻啦 逼翼跳票了 现在这门语言我们两个来做决定就好了 @thautwarm

**Comment by thautwarm** [comment]
意料之中。。。

2017年9月18日 10:08，"Tesla Ice Zhang" <notifications@github.com<mailto:notifications@github.com>>写道：

大新闻啦 逼翼跳票了 现在这门语言我们两个来做决定就好了 @thautwarm<https://github.com/thautwarm>

**Comment by CodeForCSharp** [comment]
简直有趣，你们这搞得什么

发送自 Windows 10 版邮件应用

发件人: thautwarm
发送时间: 2017年9月18日 16:12
收件人: Cm-lang/Cmc
抄送: Subscribed
主题: Re: [Cm-lang/Cmc] Choosing a LLVM binding for C# (#5)

意料之中。。。 

2017年9月18日 10:08，"Tesla Ice Zhang" <notifications@github.com<mailto:notifications@github.com>>写道： 

大新闻啦 逼翼跳票了 现在这门语言我们两个来做决定就好了 @thautwarm<https://github.com/thautwarm>

**Comment by thautwarm** [comment]
我也不清楚。。。蕙芷写语言不？？？

2017年9月18日 下午4:13，"CodeForCSharp" <notifications@github.com<mailto:notifications@github.com>>写道：
简直有趣，你们这搞得什么

发送自 Windows 10 版邮件应用

发件人: thautwarm
发送时间: 2017年9月18日 16:12
收件人: Cm-lang/Cmc
抄送: Subscribed
主题: Re: [Cm-lang/Cmc] Choosing a LLVM binding for C# (#5)

意料之中。。。

2017年9月18日 10:08，"Tesla Ice Zhang" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com>>>写道：

大新闻啦 逼翼跳票了 现在这门语言我们两个来做决定就好了 @thautwarm<https://github.com/thautwarm>

**Comment by AkimotoAkari** [comment]
@ice1000 However I'm really poor in that... Yep actually getting 8086 binaries is quite awesome:)
